#! /bin/sh

mode=cvs


lasttag=`cvs log -h version.c |
	sed '1,/symbolic names:/d' |
	head -1 |
	awk '{print $1}' |
	sed 's/://'`

version_line=`grep -i version version.c | head -1`
if [ "$version_line" = "" ]
then
	version_line=`head -1 version.c`
fi

ver=`expr "$version_line" : '[^0-9]*\([0-9._]*\)' | sed 's/.*\.//'`

newtag=V$ver

if [ "$lasttag" = "$newtag" ]
then
	echo "error: need to update version.c"
	echo "last tag $lasttag"
	exit 1
fi

head -3 ChangeLog | tail -1 | grep $newtag > /dev/null 2>&1
if [ $? != 0 ]
then
	echo "error: ChangeLog out of date: $newtag"
	exit 1
fi

msg=`cat ChangeLog | 
	sed -n -e "1{h;n}; /^[0-9]/{x;p}; /\<$lasttag\>/Q; /^[0-9]/!H"`

# diffstat output generation
diffstat=`which diffstat 2>&1`
if [ -e "$diffstat" ]
then
sep=$'\x0a\x0a=== diffstat output ===\x0a\x0a'
msgstat=`cvs diff -r $lasttag | $diffstat -w 70`
fi

echo "prev tag $lasttag; new tag $newtag"
echo "====== LOG MESSAGE ====="
echo "$msg$sep$msgstat"
echo "========================"

echo -n "Ok? "

read x

if [ "$x" != "y" ]
then
	exit 1
fi

cvs -z9 commit -R -m "$msg$sep$msgstat"
if [ $? != 0 ]
then
    echo "error during cvs commit"
    exit 1
fi
cvs -z9 tag -R $newtag
