#! /bin/sh

# this makes a tarball of the sources plus the media files

# you probably want to be in a fresh directory (separate from the sources)
# when you run it

if [ $# != 1 ]
then
    echo "usage: make-tarball version-string"
    exit 1
fi

rel="$1"

rm -rf TMP
mkdir TMP

cd TMP

if [ -z "$CVSROOT" ]
then
    CVSROOT=:ext:raceintospace.cvs.sourceforge.net:/cvsroot/raceintospace
    export CVSROOT
fi

cvs -z8 export -D now race
cvs -z8 export -D now gamedat

dir=raceintospace-${rel}
mv race ${dir}
cd ${dir}
mv ../gamedat gamedata

# you need to already have done
# git clone \
#  ssh://SFNAME@raceintospace.git.sourceforge.net/gitroot/raceintospace/avdata

(cd ~/race/avdata && git archive --format=tar HEAD) | tar -xf -

aclocal -I m4
autoconf
rm -rf autom4te.cache

cd ..
tar -czf ../${dir}.tar.gz ${dir}

