#! /bin/sh -e

# this makes a tarball of the sources plus the media files

# the files for race and gamedat come from the sourceforge server,
# so won't include any uncommitted changes you have locally

# you need to be in a directory with subdirectories race gamedat and avdata

if [ $# != 1 ]
then
    echo "usage: make-tarball version-string"
    exit 1
fi

rel="$1"

if [ ! -d race -o ! -d gamedat -o ! -d avdata ]
then
    echo "bad directory structure - see os_linux/README"
    exit 1
fi

outname=raceintospace-${rel}.tar.gz
if [ -f ${outname} ]
then
    echo -n "ok to remove and recreate ${outname}? (y/n) "
    read x
    if [ "$x" != "y" ]
    then
	echo "aborted"
	exit 1
    fi
fi

if [ -d TMP.build ]
then
    echo -n "ok to remove subdirectory TMP.build? (y/n) "
    read x
    if [ "$x" != "y" ]
    then
	echo "aborted"
	exit 1
    fi
fi

echo ""
echo "making: ${outname}"
echo "note - top of debian/changelog is:"
head -1 race/debian/changelog
echo ""

rm -rf TMP.build
mkdir TMP.build

cd TMP.build

if [ -z "$CVSROOT" ]
then
    CVSROOT=:ext:raceintospace.cvs.sourceforge.net:/cvsroot/raceintospace
    export CVSROOT
fi

cvs -z8 export -D now race
cvs -z8 export -D now gamedat

dir=raceintospace-${rel}
mv race ${dir}

mv gamedat ${dir}/gamedata

(cd ../avdata && git archive --format=tar HEAD) | tar -C ${dir} -xf -

(
    cd ${dir}
    aclocal -I m4
    autoconf
    rm -rf autom4te.cache
)

tar -czf ../${outname} ${dir}
