#! /bin/sh

name=raceintospace
ver=0.2

name_ver=${name}-${ver}

set -x
make tar
rm -rf TMP
mkdir -p TMP/$name_ver
cat $name.tar.gz | (cd TMP/$name_ver; tar -xzf -)
(cd TMP; tar -czf ~/rpmbuild/SOURCES/${name_ver}.tar.gz ${name_ver})

sed "s/@VER@/$ver/" < $name.spec > ~/rpmbuild/SPECS/$name.spec

rpmbuild -ba ~/rpmbuild/SPECS/$name.spec

cp ~/rpmbuild/RPMS/i386/${name}-${ver}-1.i386.rpm ~/race-release
cp $name.tar.gz ~/race-release/${name}-${ver}.tar.gz

echo -n "send to sourceforge? "
read x

if [ "$x" = "y" ]
then
    ncftpput upload.sourceforge.net /incoming \
	~/race-release/${name}-${ver}.tar.gz \
	~/race-release/${name}-${ver}-1.i386.rpm
fi
